[workspace]
resolver = "2"
members = ["kiro-client", "kiro-proto"]

[workspace.dependencies]
# Local dependencies
kiro-client = { path = "kiro-client" }
kiro-proto = { path = "kiro-proto" }

# Global dependencies
axum = "0.7.5"
dotenv = "0.15.0"
http = "1.1.0"
tokio = "1.39.3"
tonic = "0.12.1"
tower-http = "0.5.2"
tracing = "0.1.40"
serde = "1.0.130"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
