version: "3.9"
name: grpc-api-client
services:
  # ------------------- surrealdb ----------------------
  storage:
    container_name: surrealdb
    image: surrealdb/surrealdb:latest
    user: ${SURREAL_USER:-root}
    restart: unless-stopped
    command: start --strict --auth --user ${SURREAL_USER:-root} --pass ${SURREAL_PASS:-root} --log ${SURREAL_LOG_LEVEL:-info} file:/data/database.db --allow-scripting
    environment:
      USER: ${SURREAL_USER:-root}
      PASS: ${SURREAL_PASS:-root}
      ADDR: ${SURREAL_DB_HOST:-0.0.0.0/0}
    volumes:
      - surrealdb_data:/data:rw
    networks:
      - default
    ports:
      - ${SURREAL_PORT}:8000
  # ------------------- Jaeger ----------------------
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    restart: unless-stopped
    ports:
      - 16686:16686
      - 4317:4317
    networks:
      - default
# ------------------- Networks ----------------------
networks:
  default:
    driver: bridge
# ------------------- Storage ----------------------
volumes:
  surrealdb_data:
