services:
  # ------------------- kiro ---------------------------
  kiro:
    build:
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - ./:/kiro
    depends_on:
      - surrealdb
      - jaeger
    environment:
      - SURREAL_DB_HOST=surrealdb
      - JAEGER_AGENT_HOST=jaeger
    ports:
      - "8080:8080"
  # ------------------- surrealdb ----------------------
  surrealdb:
    image: surrealdb/surrealdb:latest
    user: ${SURREAL_USER:-root}
    restart: unless-stopped
    command:
      - start
      - --strict
      - --auth
      - --user=${SURREAL_USER:-root}
      - --pass=${SURREAL_PASS:-root}
      - --log=${SURREAL_LOG_LEVEL:-info}
      - file:/data/database.db
      - --allow-scripting
    depends_on:
      - jaeger
    volumes:
      - ./:/kiro/surrealdb/data:rw
    networks:
      - default
    ports:
      - ${SURREAL_PORT}:8000
  # ------------------- Jaeger ----------------------
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    restart: unless-stopped
    ports:
      - 16686:16686
      - 4317:4317
    networks:
      - default
# ------------------- Networks ----------------------
networks:
  default:
    driver: bridge
